version: '3'
services:
  latex:
    build: .
    platform: linux/arm64
    entrypoint:
      - bash
      - scripts/merge-bib.sh
    volumes:
      - data:/data

  cloudref:
    image: jabref/cloudref
    platform: linux/amd64
    ports:
      - 80:8080
    volumes:
      - data:/root/CloudRef

volumes:
  data:
